/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

import seguridad.Conexion;
import seguridad.Usuario;

/**
 *
 * @author GuillePC
 */
public class Balance extends javax.swing.JFrame {
    private static Usuario user;//variable global del usuario logeado

    /**
     * Creates new form Lotes
     */
    
   
     public Balance(Usuario user) throws SQLException {
        this.user=user;
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/índice.png")).getImage());
         
        initComponents();
        try{
            Connection cn=Conexion.conectar();         
        
        this.setLocationRelativeTo(null);
        String sql = "SELECT SUM(ve.Total) FROM venta ve WHERE ve.Anulado=0;";
        String sql2 = "SELECT SUM(lo.Costo) FROM lote lo INNER JOIN compra co ON lo.Compra_idCompra = co.idCompra;";
       
        Statement st=cn.createStatement();
        ResultSet rs=st.executeQuery(sql);
        String dat[] = new String[3];
        while(rs.next())
                {
                    dat[0]=rs.getString(1);
                    BalancedeSaldos.setValueAt(dat[0], 15, 3);
                    //jtxtTotalVentas.setText(dat[0]);
                 }
        
        
        ResultSet rs2=st.executeQuery(sql2);
        String dat2[] = new String[3];
        while(rs2.next())
                {
                    dat2[0]=rs2.getString(1);
                    BalancedeSaldos.setValueAt(dat2[0], 9, 2);
                    //jtxtTotalCompras.setText(dat2[0]);
                 }
        
        //int tv= Integer.parseInt( jtxtTotalVentas.getText() )  ;
        //int tc= Integer.parseInt( jtxtTotalCompras.getText() )  ;
        //jtxtUtilidad.setText( String.valueOf(tv-tc) );

        }
        catch(SQLException ex)
        {
          JOptionPane.showMessageDialog(null, "Error "+ex);
        }
    }
     
           
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpopOpciones = new javax.swing.JPopupMenu();
        jMenuComprar = new javax.swing.JMenuItem();
        jmenuModificar = new javax.swing.JMenuItem();
        jmenuEliminar = new javax.swing.JMenuItem();
        GrupoBotones = new javax.swing.ButtonGroup();
        GrupoBotones2 = new javax.swing.ButtonGroup();
        BalanceCalcu = new javax.swing.JLabel();
        Calcular = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jLabelMenu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BalancedeSaldos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jMenuComprar.setText("Comprar");
        jMenuComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuComprarActionPerformed(evt);
            }
        });
        jpopOpciones.add(jMenuComprar);

        jmenuModificar.setText("Modificar");
        jmenuModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuModificarActionPerformed(evt);
            }
        });
        jpopOpciones.add(jmenuModificar);

        jmenuEliminar.setText("Eliminar");
        jmenuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuEliminarActionPerformed(evt);
            }
        });
        jpopOpciones.add(jmenuEliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BALANCE DE SALDOS");
        setMinimumSize(new java.awt.Dimension(1150, 690));
        setResizable(false);
        getContentPane().setLayout(null);

        BalanceCalcu.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        BalanceCalcu.setForeground(new java.awt.Color(255, 255, 255));
        BalanceCalcu.setText("Calcular Balance");
        getContentPane().add(BalanceCalcu);
        BalanceCalcu.setBounds(510, 570, 100, 20);

        Calcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contabilidad.png"))); // NOI18N
        Calcular.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Calcular Balance</h2>\n\t</div>\n</body>\n</html>");
        Calcular.setBorderPainted(false);
        Calcular.setContentAreaFilled(false);
        Calcular.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contabilidad negro.png"))); // NOI18N
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });
        getContentPane().add(Calcular);
        Calcular.setBounds(510, 500, 80, 70);

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cerrar Sesion.png"))); // NOI18N
        btnMenu.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Menu</h2>\n\t</div>\n</body>\n</html>");
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CerrarSesionNegro.png"))); // NOI18N
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu);
        btnMenu.setBounds(1010, 550, 73, 49);

        jLabelMenu.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabelMenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMenu.setText("Menú");
        getContentPane().add(jLabelMenu);
        jLabelMenu.setBounds(1020, 600, 50, 21);

        BalancedeSaldos.setBackground(new java.awt.Color(240, 240, 240));
        BalancedeSaldos.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        BalancedeSaldos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Caja", null, null, null},
                {"Bancos", null, null, ""},
                {"Clientes", null, null, null},
                {"Deudores", null, null, null},
                {"Cuentas por cobrar", null, null, null},
                {"IVA por cobrar", null, null, null},
                {"Mercaderías", null, null, null},
                {"Sistema de Cómputo", null, null, null},
                {"Caja Chica", null, null, null},
                {"Compras", null, null, null},
                {"Gastos Generales", null, null, null},
                {"Depreciación Sistema de Cómputo", null, null, null},
                {"Valor Residual Sistema de Cómputo", null, null, null},
                {"", "Proveedores", null, null},
                {null, "Acreedores", null, null},
                {null, "Ventas", null, null},
                {null, "IVA por pagar", null, null},
                {null, "Dep. Acum. Sistema de Cómputo", null, null},
                {null, "Valor Residual Acum. Sistema de Cómputo", null, null},
                {null, "Capital", null, null},
                {null, "Balance", null, null}
            },
            new String [] {
                "ACTIVO", "PASIVO", "", ""
            }
        ));
        BalancedeSaldos.setSelectionBackground(new java.awt.Color(128, 128, 128));
        BalancedeSaldos.setSelectionForeground(new java.awt.Color(240, 240, 240));
        jScrollPane1.setViewportView(BalancedeSaldos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 100, 910, 370);

        jLabel1.setBackground(new java.awt.Color(38, 76, 114));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(980, 600));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1150, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void jMenuComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuComprarActionPerformed

    }//GEN-LAST:event_jMenuComprarActionPerformed

    private void jmenuModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuModificarActionPerformed
       
    }//GEN-LAST:event_jmenuModificarActionPerformed

    private void jmenuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuEliminarActionPerformed

      
    }//GEN-LAST:event_jmenuEliminarActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        Menu otro = new Menu();
        otro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed

        
//      int tv= Integer.parseInt( BalancedeSaldos.getValueAt(15, 3).toString() )  ;
//      int tc= Integer.parseInt( BalancedeSaldos.getValueAt(9, 2).toString() ) ;
      double sum_ac=0;
      DefaultTableModel tm = (DefaultTableModel) BalancedeSaldos.getModel();
      for(int i=0; i<13; i++)
      {
          if(BalancedeSaldos.getValueAt(i,2)== null)
          {
              BalancedeSaldos.setValueAt(0,i,2);
          }
          sum_ac= sum_ac + Double.parseDouble(String.valueOf(tm.getValueAt(i,2)));          
      }
      BalancedeSaldos.setValueAt(sum_ac, 20, 2);
      BalancedeSaldos.setValueAt(sum_ac, 20, 3);
      double sum_pa=0;
      for(int j=13; j<19; j++)
      {
          if(BalancedeSaldos.getValueAt(j,3)== null)
          {
              BalancedeSaldos.setValueAt(0,j,3);
          }
          sum_pa= sum_pa + Double.parseDouble(String.valueOf(tm.getValueAt(j,3)));          
      }
      double cap = sum_ac-sum_pa;
      BalancedeSaldos.setValueAt(cap, 19, 3);
        //jtxtUtilidad.setText( String.valueOf(tv-tc) );  
    }//GEN-LAST:event_CalcularActionPerformed

     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Balance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Balance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Balance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Balance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               try {
                    new Balance(user).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Estadisticas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BalanceCalcu;
    private javax.swing.JTable BalancedeSaldos;
    private javax.swing.JButton Calcular;
    private javax.swing.ButtonGroup GrupoBotones;
    private javax.swing.ButtonGroup GrupoBotones2;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JMenuItem jMenuComprar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jmenuEliminar;
    private javax.swing.JMenuItem jmenuModificar;
    private javax.swing.JPopupMenu jpopOpciones;
    // End of variables declaration//GEN-END:variables
}
