/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

import seguridad.Conexion;
import seguridad.Usuario;

/**
 *
 * @author GuillePC
 */
public class Estadisticas extends javax.swing.JFrame {
    private static Usuario user;//variable global del usuario logeado

    /**
     * Creates new form Lotes
     */
    
   
     public Estadisticas(Usuario user) throws SQLException {
        this.user=user;//Se asigna el usuaario que hizo login
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/índice.png")).getImage());
         
        initComponents();
        try{
            Connection cn=Conexion.conectar();         
        
        this.setLocationRelativeTo(null);
        String sql = "SELECT SUM(ve.Total) FROM venta ve WHERE ve.Anulado=0;";
        String sql2 = "SELECT SUM(lo.Costo) FROM lote lo INNER JOIN compra co ON lo.Compra_idCompra = co.idCompra;";
       
        Statement st=cn.createStatement();
        ResultSet rs=st.executeQuery(sql);
        String dat[] = new String[3];
        while(rs.next())
                {
                    dat[0]=rs.getString(1);
                    jtxtTotalVentas.setText(dat[0]);
                 }
        
        
        ResultSet rs2=st.executeQuery(sql2);
        String dat2[] = new String[3];
        while(rs2.next())
                {
                    dat2[0]=rs2.getString(1);
                    jtxtTotalCompras.setText(dat2[0]);
                 }
        
        int tv= Integer.parseInt( jtxtTotalVentas.getText() )  ;
        int tc= Integer.parseInt( jtxtTotalCompras.getText() )  ;
        jtxtUtilidad.setText( String.valueOf(tv-tc) );
        jtxtPorcentajeUt.setText( String.valueOf((tv-tc)*100/tv) +"%");

        }
        catch(SQLException ex)
        {
          JOptionPane.showMessageDialog(null, "Error "+ex);
        }
    }
     
           
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpopOpciones = new javax.swing.JPopupMenu();
        jMenuComprar = new javax.swing.JMenuItem();
        jmenuModificar = new javax.swing.JMenuItem();
        jmenuEliminar = new javax.swing.JMenuItem();
        GrupoBotones = new javax.swing.ButtonGroup();
        GrupoBotones2 = new javax.swing.ButtonGroup();
        jLabelBalance = new javax.swing.JLabel();
        AbrirBalance = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jLabelMenu = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtxtPorcentajeUt = new javax.swing.JTextField();
        jtxtUtilidad = new javax.swing.JTextField();
        jtxtTotalVentas = new javax.swing.JTextField();
        jtxtTotalCompras = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jMenuComprar.setText("Comprar");
        jMenuComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuComprarActionPerformed(evt);
            }
        });
        jpopOpciones.add(jMenuComprar);

        jmenuModificar.setText("Modificar");
        jmenuModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuModificarActionPerformed(evt);
            }
        });
        jpopOpciones.add(jmenuModificar);

        jmenuEliminar.setText("Eliminar");
        jmenuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuEliminarActionPerformed(evt);
            }
        });
        jpopOpciones.add(jmenuEliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ESTADISTICAS");
        setMinimumSize(new java.awt.Dimension(1150, 690));
        setResizable(false);
        setSize(new java.awt.Dimension(1150, 690));
        getContentPane().setLayout(null);

        jLabelBalance.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabelBalance.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBalance.setText("Balance General");
        getContentPane().add(jLabelBalance);
        jLabelBalance.setBounds(40, 600, 140, 20);

        AbrirBalance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/balanza-para-pesar blanca.png"))); // NOI18N
        AbrirBalance.setBorderPainted(false);
        AbrirBalance.setContentAreaFilled(false);
        AbrirBalance.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/balanza-para-pesar.png"))); // NOI18N
        AbrirBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirBalanceActionPerformed(evt);
            }
        });
        getContentPane().add(AbrirBalance);
        AbrirBalance.setBounds(70, 540, 70, 60);

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cerrar Sesion.png"))); // NOI18N
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CerrarSesionNegro.png"))); // NOI18N
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu);
        btnMenu.setBounds(1040, 560, 73, 49);

        jLabelMenu.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabelMenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMenu.setText("Menú");
        getContentPane().add(jLabelMenu);
        jLabelMenu.setBounds(1050, 610, 60, 17);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total Ventas");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(310, 150, 130, 17);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("% UTILIDAD");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(310, 390, 90, 18);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Total Compras");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(310, 230, 130, 17);

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("UTILIDAD");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(310, 310, 130, 17);

        jtxtPorcentajeUt.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jtxtPorcentajeUt.setEnabled(false);
        getContentPane().add(jtxtPorcentajeUt);
        jtxtPorcentajeUt.setBounds(550, 380, 170, 30);

        jtxtUtilidad.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jtxtUtilidad.setEnabled(false);
        getContentPane().add(jtxtUtilidad);
        jtxtUtilidad.setBounds(550, 300, 170, 30);

        jtxtTotalVentas.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jtxtTotalVentas.setEnabled(false);
        getContentPane().add(jtxtTotalVentas);
        jtxtTotalVentas.setBounds(550, 140, 170, 30);

        jtxtTotalCompras.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jtxtTotalCompras.setEnabled(false);
        jtxtTotalCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalComprasActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtTotalCompras);
        jtxtTotalCompras.setBounds(550, 220, 170, 30);

        jLabel1.setBackground(new java.awt.Color(38, 76, 114));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(1150, 690));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1150, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void jMenuComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuComprarActionPerformed

    }//GEN-LAST:event_jMenuComprarActionPerformed

    private void jmenuModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuModificarActionPerformed
       
    }//GEN-LAST:event_jmenuModificarActionPerformed

    private void jmenuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuEliminarActionPerformed

       
    }//GEN-LAST:event_jmenuEliminarActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        Menu otro = new Menu();
        otro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void jtxtTotalComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalComprasActionPerformed

    private void AbrirBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirBalanceActionPerformed
        Balance B;
          try {
              B = new Balance(user);
              B.setVisible(true);
          } catch (SQLException ex) {
              Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
          }        
        this.setVisible(false);
    }//GEN-LAST:event_AbrirBalanceActionPerformed

     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Estadisticas(user).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Estadisticas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbrirBalance;
    private javax.swing.ButtonGroup GrupoBotones;
    private javax.swing.ButtonGroup GrupoBotones2;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabelBalance;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JMenuItem jMenuComprar;
    private javax.swing.JMenuItem jmenuEliminar;
    private javax.swing.JMenuItem jmenuModificar;
    private javax.swing.JPopupMenu jpopOpciones;
    private javax.swing.JTextField jtxtPorcentajeUt;
    private javax.swing.JTextField jtxtTotalCompras;
    private javax.swing.JTextField jtxtTotalVentas;
    private javax.swing.JTextField jtxtUtilidad;
    // End of variables declaration//GEN-END:variables
}
