/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;
import java.sql.ResultSet;
import java.sql.Connection;
import javax.swing.ImageIcon;
import seguridad.Usuario;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author GuillePC
 */
public class Menu extends javax.swing.JFrame {
      private static Usuario user;//variable global del usuario logeado

    /**
     * Creates new form Menup
     */

      
     public Menu()
     {
           initComponents();
        this.user=user;//Se asigna el usuaario que hizo login
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/índice.png")).getImage());
     
     }
    
    
     public Menu(Usuario user) {//metodo constructor que recibe el usuario logeados
        initComponents();
        this.user=user;//Se asigna el usuaario que hizo login
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/índice.png")).getImage());
        
    }

    
     public void seguridad(){
        System.out.println("nivel de acceso: "+user.getNivelAcceso());
        if(user.getNivelAcceso()==1){
            btnAddUser.setVisible(true);
            BtnProveedor.setVisible(true);
            btnNuevacompra.setVisible(true);
            btnInventario.setVisible(true);
            btnEstadisticas.setVisible(true);
        }else if(user.getNivelAcceso()==2){
            btnAddUser.setVisible(false);
            BtnProveedor.setVisible(false);
            btnNuevacompra.setVisible(true);
            btnInventario.setVisible(true);
            btnEstadisticas.setVisible(false);        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInventario = new javax.swing.JButton();
        BtnProveedor = new javax.swing.JButton();
        btnNuevacompra = new javax.swing.JButton();
        btnEstadisticas = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnAddUser = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnMedicamento = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        btnNuevaVenta = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU");
        setMinimumSize(new java.awt.Dimension(1150, 690));
        setResizable(false);
        setSize(new java.awt.Dimension(1150, 690));
        getContentPane().setLayout(null);

        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ListaBlanco.png"))); // NOI18N
        btnInventario.setBorderPainted(false);
        btnInventario.setContentAreaFilled(false);
        btnInventario.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ListaNegro.png"))); // NOI18N
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInventario);
        btnInventario.setBounds(120, 280, 70, 70);

        BtnProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EquipoProveedorBlanco.png"))); // NOI18N
        BtnProveedor.setBorderPainted(false);
        BtnProveedor.setContentAreaFilled(false);
        BtnProveedor.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EquipoProveedorNegro.png"))); // NOI18N
        BtnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(BtnProveedor);
        BtnProveedor.setBounds(450, 450, 80, 80);

        btnNuevacompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AñadirCarritoBlanco.png"))); // NOI18N
        btnNuevacompra.setBorderPainted(false);
        btnNuevacompra.setContentAreaFilled(false);
        btnNuevacompra.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AñadirCarritoNegro.png"))); // NOI18N
        btnNuevacompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevacompraActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevacompra);
        btnNuevacompra.setBounds(600, 280, 90, 80);

        btnEstadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EstadisticasBlanco.png"))); // NOI18N
        btnEstadisticas.setBorderPainted(false);
        btnEstadisticas.setContentAreaFilled(false);
        btnEstadisticas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EstadisticasNegro.png"))); // NOI18N
        btnEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasActionPerformed(evt);
            }
        });
        getContentPane().add(btnEstadisticas);
        btnEstadisticas.setBounds(120, 460, 70, 70);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cerrar Sesion.png"))); // NOI18N
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CerrarSesionNegro.png"))); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar);
        btnCerrar.setBounds(1040, 30, 50, 50);

        btnAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/UsuarioBlanco.png"))); // NOI18N
        btnAddUser.setBorderPainted(false);
        btnAddUser.setContentAreaFilled(false);
        btnAddUser.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/UsuarioNegro.png"))); // NOI18N
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddUser);
        btnAddUser.setBounds(780, 460, 70, 73);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono.png"))); // NOI18N
        Logo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Logo);
        Logo.setBounds(30, 20, 140, 130);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cerrar Sesión");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(1000, 80, 120, 30);

        btnMedicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MaletinBlanco.png"))); // NOI18N
        btnMedicamento.setBorderPainted(false);
        btnMedicamento.setContentAreaFilled(false);
        btnMedicamento.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MaletinNegro.png"))); // NOI18N
        btnMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicamentoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMedicamento);
        btnMedicamento.setBounds(270, 280, 110, 73);

        btnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CarritoComprasBlanco.png"))); // NOI18N
        btnCompras.setBorderPainted(false);
        btnCompras.setContentAreaFilled(false);
        btnCompras.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CarritoComprasNegro.png"))); // NOI18N
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });
        getContentPane().add(btnCompras);
        btnCompras.setBounds(430, 270, 100, 90);

        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VentasDineroBlanco.png"))); // NOI18N
        btnVentas.setBorderPainted(false);
        btnVentas.setContentAreaFilled(false);
        btnVentas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VentasDineroNegro.png"))); // NOI18N
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        getContentPane().add(btnVentas);
        btnVentas.setBounds(750, 270, 97, 90);

        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ClientesBlanco.png"))); // NOI18N
        btnClientes.setBorderPainted(false);
        btnClientes.setContentAreaFilled(false);
        btnClientes.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ClientesNegro.png"))); // NOI18N
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnClientes);
        btnClientes.setBounds(620, 450, 70, 100);

        btnHistorial.setBackground(new java.awt.Color(255, 255, 255));
        btnHistorial.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AAA.png"))); // NOI18N
        btnHistorial.setBorderPainted(false);
        btnHistorial.setContentAreaFilled(false);
        btnHistorial.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AAA2.png"))); // NOI18N
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });
        getContentPane().add(btnHistorial);
        btnHistorial.setBounds(280, 450, 80, 80);

        btnNuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/NVentaBlanco.png"))); // NOI18N
        btnNuevaVenta.setBorderPainted(false);
        btnNuevaVenta.setContentAreaFilled(false);
        btnNuevaVenta.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/NVentaNegro.png"))); // NOI18N
        btnNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaVentaActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevaVenta);
        btnNuevaVenta.setBounds(900, 270, 97, 90);

        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/UsuarioNuevoBlanco.png"))); // NOI18N
        btnUsuarios.setBorderPainted(false);
        btnUsuarios.setContentAreaFilled(false);
        btnUsuarios.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/UsuarioNuevoNegro.png"))); // NOI18N
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnUsuarios);
        btnUsuarios.setBounds(920, 450, 80, 80);

        jLabel2.setFont(new java.awt.Font("Modern No. 20", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("\"Senda de Vida\"");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(460, 90, 320, 100);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nueva Venta");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(900, 360, 110, 21);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Usuarios");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(930, 540, 70, 21);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Medicamentos");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(270, 360, 120, 21);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Compras");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(450, 360, 70, 21);

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nueva Compra");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(590, 360, 120, 21);

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ventas");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(770, 360, 60, 21);

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Inventario");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(110, 360, 90, 21);

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Estadísticas");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(110, 540, 100, 21);

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Historial");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(290, 540, 80, 21);

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Proveedores");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(440, 540, 100, 21);

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Clientes");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(620, 540, 80, 21);

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Crear Usuario");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(760, 540, 110, 21);

        jLabel3.setFont(new java.awt.Font("Modern No. 20", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sanatorio");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(520, 40, 200, 100);

        jLabel1.setBackground(new java.awt.Color(38, 76, 114));
        jLabel1.setMinimumSize(new java.awt.Dimension(1150, 690));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(1150, 690));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1150, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        Inventario in = new Inventario(user);
        in.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnInventarioActionPerformed

    private void BtnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProveedorActionPerformed
        Proveedores Provee = new Proveedores(user);
        Provee.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnProveedorActionPerformed

    private void btnNuevacompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevacompraActionPerformed
        NuevaCompra nuev = new NuevaCompra(user);
        nuev.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnNuevacompraActionPerformed

    private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed
        Estadisticas Es;
          try {
              Es = new Estadisticas(user);
              Es.setVisible(true);
          } catch (SQLException ex) {
              Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
          }        
        this.setVisible(false);
    }//GEN-LAST:event_btnEstadisticasActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        inicio otro = new inicio();
        otro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
      CrearUsuario cu = new CrearUsuario();
      cu.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicamentoActionPerformed

        Medicamento med = new Medicamento(user);
        med.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnMedicamentoActionPerformed

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        Compras Comprass = new Compras(user);
        Comprass.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnComprasActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        Clientes cliente = new Clientes(user);
        cliente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        Historial his = new Historial(user);
        his.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
       Ventas vent = new Ventas(user);
       vent.setVisible(true);
       this.setVisible(false);
               
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaVentaActionPerformed
        NuevaVenta NVenta = new NuevaVenta(user);
        NVenta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNuevaVentaActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        Usuarios us = new Usuarios();
        us.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {               
                new Menu(user).setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnProveedor;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnMedicamento;
    private javax.swing.JButton btnNuevaVenta;
    private javax.swing.JButton btnNuevacompra;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
